/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerCareerIdRouteImport } from './routes/career/$career-id'
import { Route as CareerCareerIdSubjectSubjectIdRouteImport } from './routes/career/$career-id/subject/$subject-id'
import { Route as CareerCareerIdSubjectSubjectIdNewDocumentRouteImport } from './routes/career/$career-id/subject/$subject-id/new-document'
import { Route as CareerCareerIdSubjectSubjectIdNewEvaluationRouteImport } from './routes/career/$career-id/subject/$subject-id/new-evaluation'
import { Route as CareerCareerIdSubjectSubjectIdDocumentDocumentIdRouteImport } from './routes/career/$career-id/subject/$subject-id/document/$document-id'
import { Route as CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRouteImport } from './routes/career/$career-id/subject/$subject-id/evaluation/$evaluation-id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCareerIdRoute = CareerCareerIdRouteImport.update({
  id: '/career/$career-id',
  path: '/career/$career-id',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCareerIdSubjectSubjectIdRoute =
  CareerCareerIdSubjectSubjectIdRouteImport.update({
    id: '/subject/$subject-id',
    path: '/subject/$subject-id',
    getParentRoute: () => CareerCareerIdRoute,
  } as any)
const CareerCareerIdSubjectSubjectIdNewDocumentRoute =
  CareerCareerIdSubjectSubjectIdNewDocumentRouteImport.update({
    id: '/new-document',
    path: '/new-document',
    getParentRoute: () => CareerCareerIdSubjectSubjectIdRoute,
  } as any)
const CareerCareerIdSubjectSubjectIdNewEvaluationRoute =
  CareerCareerIdSubjectSubjectIdNewEvaluationRouteImport.update({
    id: '/new-evaluation',
    path: '/new-evaluation',
    getParentRoute: () => CareerCareerIdSubjectSubjectIdRoute,
  } as any)
const CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute =
  CareerCareerIdSubjectSubjectIdDocumentDocumentIdRouteImport.update({
    id: '/document/$document-id',
    path: '/document/$document-id',
    getParentRoute: () => CareerCareerIdSubjectSubjectIdRoute,
  } as any)
const CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute =
  CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRouteImport.update({
    id: '/evaluation/$evaluation-id',
    path: '/evaluation/$evaluation-id',
    getParentRoute: () => CareerCareerIdSubjectSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career/$career-id': typeof CareerCareerIdRouteWithChildren
  '/career/$career-id/subject/$subject-id': typeof CareerCareerIdSubjectSubjectIdRouteWithChildren
  '/career/$career-id/subject/$subject-id/new-document': typeof CareerCareerIdSubjectSubjectIdNewDocumentRoute
  '/career/$career-id/subject/$subject-id/new-evaluation': typeof CareerCareerIdSubjectSubjectIdNewEvaluationRoute
  '/career/$career-id/subject/$subject-id/document/$document-id': typeof CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute
  '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id': typeof CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career/$career-id': typeof CareerCareerIdRouteWithChildren
  '/career/$career-id/subject/$subject-id': typeof CareerCareerIdSubjectSubjectIdRouteWithChildren
  '/career/$career-id/subject/$subject-id/new-document': typeof CareerCareerIdSubjectSubjectIdNewDocumentRoute
  '/career/$career-id/subject/$subject-id/new-evaluation': typeof CareerCareerIdSubjectSubjectIdNewEvaluationRoute
  '/career/$career-id/subject/$subject-id/document/$document-id': typeof CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute
  '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id': typeof CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career/$career-id': typeof CareerCareerIdRouteWithChildren
  '/career/$career-id/subject/$subject-id': typeof CareerCareerIdSubjectSubjectIdRouteWithChildren
  '/career/$career-id/subject/$subject-id/new-document': typeof CareerCareerIdSubjectSubjectIdNewDocumentRoute
  '/career/$career-id/subject/$subject-id/new-evaluation': typeof CareerCareerIdSubjectSubjectIdNewEvaluationRoute
  '/career/$career-id/subject/$subject-id/document/$document-id': typeof CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute
  '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id': typeof CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career/$career-id'
    | '/career/$career-id/subject/$subject-id'
    | '/career/$career-id/subject/$subject-id/new-document'
    | '/career/$career-id/subject/$subject-id/new-evaluation'
    | '/career/$career-id/subject/$subject-id/document/$document-id'
    | '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career/$career-id'
    | '/career/$career-id/subject/$subject-id'
    | '/career/$career-id/subject/$subject-id/new-document'
    | '/career/$career-id/subject/$subject-id/new-evaluation'
    | '/career/$career-id/subject/$subject-id/document/$document-id'
    | '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id'
  id:
    | '__root__'
    | '/'
    | '/career/$career-id'
    | '/career/$career-id/subject/$subject-id'
    | '/career/$career-id/subject/$subject-id/new-document'
    | '/career/$career-id/subject/$subject-id/new-evaluation'
    | '/career/$career-id/subject/$subject-id/document/$document-id'
    | '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerCareerIdRoute: typeof CareerCareerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/$career-id': {
      id: '/career/$career-id'
      path: '/career/$career-id'
      fullPath: '/career/$career-id'
      preLoaderRoute: typeof CareerCareerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/$career-id/subject/$subject-id': {
      id: '/career/$career-id/subject/$subject-id'
      path: '/subject/$subject-id'
      fullPath: '/career/$career-id/subject/$subject-id'
      preLoaderRoute: typeof CareerCareerIdSubjectSubjectIdRouteImport
      parentRoute: typeof CareerCareerIdRoute
    }
    '/career/$career-id/subject/$subject-id/new-document': {
      id: '/career/$career-id/subject/$subject-id/new-document'
      path: '/new-document'
      fullPath: '/career/$career-id/subject/$subject-id/new-document'
      preLoaderRoute: typeof CareerCareerIdSubjectSubjectIdNewDocumentRouteImport
      parentRoute: typeof CareerCareerIdSubjectSubjectIdRoute
    }
    '/career/$career-id/subject/$subject-id/new-evaluation': {
      id: '/career/$career-id/subject/$subject-id/new-evaluation'
      path: '/new-evaluation'
      fullPath: '/career/$career-id/subject/$subject-id/new-evaluation'
      preLoaderRoute: typeof CareerCareerIdSubjectSubjectIdNewEvaluationRouteImport
      parentRoute: typeof CareerCareerIdSubjectSubjectIdRoute
    }
    '/career/$career-id/subject/$subject-id/document/$document-id': {
      id: '/career/$career-id/subject/$subject-id/document/$document-id'
      path: '/document/$document-id'
      fullPath: '/career/$career-id/subject/$subject-id/document/$document-id'
      preLoaderRoute: typeof CareerCareerIdSubjectSubjectIdDocumentDocumentIdRouteImport
      parentRoute: typeof CareerCareerIdSubjectSubjectIdRoute
    }
    '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id': {
      id: '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id'
      path: '/evaluation/$evaluation-id'
      fullPath: '/career/$career-id/subject/$subject-id/evaluation/$evaluation-id'
      preLoaderRoute: typeof CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRouteImport
      parentRoute: typeof CareerCareerIdSubjectSubjectIdRoute
    }
  }
}

interface CareerCareerIdSubjectSubjectIdRouteChildren {
  CareerCareerIdSubjectSubjectIdNewDocumentRoute: typeof CareerCareerIdSubjectSubjectIdNewDocumentRoute
  CareerCareerIdSubjectSubjectIdNewEvaluationRoute: typeof CareerCareerIdSubjectSubjectIdNewEvaluationRoute
  CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute: typeof CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute
  CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute: typeof CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute
}

const CareerCareerIdSubjectSubjectIdRouteChildren: CareerCareerIdSubjectSubjectIdRouteChildren =
  {
    CareerCareerIdSubjectSubjectIdNewDocumentRoute:
      CareerCareerIdSubjectSubjectIdNewDocumentRoute,
    CareerCareerIdSubjectSubjectIdNewEvaluationRoute:
      CareerCareerIdSubjectSubjectIdNewEvaluationRoute,
    CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute:
      CareerCareerIdSubjectSubjectIdDocumentDocumentIdRoute,
    CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute:
      CareerCareerIdSubjectSubjectIdEvaluationEvaluationIdRoute,
  }

const CareerCareerIdSubjectSubjectIdRouteWithChildren =
  CareerCareerIdSubjectSubjectIdRoute._addFileChildren(
    CareerCareerIdSubjectSubjectIdRouteChildren,
  )

interface CareerCareerIdRouteChildren {
  CareerCareerIdSubjectSubjectIdRoute: typeof CareerCareerIdSubjectSubjectIdRouteWithChildren
}

const CareerCareerIdRouteChildren: CareerCareerIdRouteChildren = {
  CareerCareerIdSubjectSubjectIdRoute:
    CareerCareerIdSubjectSubjectIdRouteWithChildren,
}

const CareerCareerIdRouteWithChildren = CareerCareerIdRoute._addFileChildren(
  CareerCareerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerCareerIdRoute: CareerCareerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
