/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject/$subjectId'
import { Route as SubjectSubjectIdDocumentIdRouteImport } from './routes/subject/$subjectId/$documentId'
import { Route as SubjectSubjectIdNewDocumentRouteImport } from './routes/subject/$subjectId/newDocument'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdDocumentIdRoute =
  SubjectSubjectIdDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => SubjectSubjectIdRoute,
  } as any)
const SubjectSubjectIdNewDocumentRoute =
  SubjectSubjectIdNewDocumentRouteImport.update({
    id: '/newDocument',
    path: '/newDocument',
    getParentRoute: () => SubjectSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/subject/$subjectId/$documentId': typeof SubjectSubjectIdDocumentIdRoute
  '/subject/$subjectId/newDocument': typeof SubjectSubjectIdNewDocumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/subject/$subjectId/$documentId': typeof SubjectSubjectIdDocumentIdRoute
  '/subject/$subjectId/newDocument': typeof SubjectSubjectIdNewDocumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/subject/$subjectId/$documentId': typeof SubjectSubjectIdDocumentIdRoute
  '/subject/$subjectId/newDocument': typeof SubjectSubjectIdNewDocumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$documentId'
    | '/subject/$subjectId/newDocument'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$documentId'
    | '/subject/$subjectId/newDocument'
  id:
    | '__root__'
    | '/'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$documentId'
    | '/subject/$subjectId/newDocument'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId/$documentId': {
      id: '/subject/$subjectId/$documentId'
      path: '/$documentId'
      fullPath: '/subject/$subjectId/$documentId'
      preLoaderRoute: typeof SubjectSubjectIdDocumentIdRouteImport
      parentRoute: typeof SubjectSubjectIdRoute
    }
    '/subject/$subjectId/newDocument': {
      id: '/subject/$subjectId/newDocument'
      path: '/newDocument'
      fullPath: '/subject/$subjectId/newDocument'
      preLoaderRoute: typeof SubjectSubjectIdNewDocumentRouteImport
      parentRoute: typeof SubjectSubjectIdRoute
    }
  }
}

interface SubjectSubjectIdRouteChildren {
  SubjectSubjectIdDocumentIdRoute: typeof SubjectSubjectIdDocumentIdRoute
  SubjectSubjectIdNewDocumentRoute: typeof SubjectSubjectIdNewDocumentRoute
}

const SubjectSubjectIdRouteChildren: SubjectSubjectIdRouteChildren = {
  SubjectSubjectIdDocumentIdRoute: SubjectSubjectIdDocumentIdRoute,
  SubjectSubjectIdNewDocumentRoute: SubjectSubjectIdNewDocumentRoute,
}

const SubjectSubjectIdRouteWithChildren =
  SubjectSubjectIdRoute._addFileChildren(SubjectSubjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
